"""Review engine — orchestrates the model call with fallback and finding tracking."""

from __future__ import annotations

from typing import Optional

from criticai.config import Config
from criticai.providers.base import get_provider


class ReviewEngine:
    """Runs the AI code review with automatic model fallback.

    Optionally accepts previous findings to enable cross-push resolution
    tracking (the model is told what it flagged last time and asked to
    mark resolved items, even if the fix was in a related area rather
    than the exact original line).
    """

    def __init__(self, config: Config) -> None:
        self._config = config

    def run(
        self,
        diff: str,
        previous_findings: Optional[str] = None,
        context: Optional[str] = None,
        rules_prompt: str = "",
        learnings_prompt: str = "",
        incremental_diff: str = "",
    ) -> Optional[str]:
        """Execute the review. Returns the review markdown, or None if all models failed.

        Args:
            diff: The full filtered PR diff text.
            previous_findings: Prior findings for resolution tracking.
            context: Additional file contents for cross-file awareness.
            rules_prompt: Custom rules from .criticai.yml to inject.
            learnings_prompt: Team learnings/suppression info.
            incremental_diff: Changes since the last review (for resolution tracking).
        """
        user_content = self._build_user_content(
            diff, previous_findings, context, incremental_diff
        )
        system_prompt = self._build_system_prompt(rules_prompt, learnings_prompt)

        # Try primary model
        try:
            return self._invoke(self._config.model, system_prompt, user_content)
        except Exception as error:
            print(f"Primary model {self._config.model!r} failed: {error}")

        # Fallback
        if not self._config.fallback_model:
            print("No fallback-model configured; giving up.")
            return None

        print(f"Falling back to {self._config.fallback_model!r}...")
        try:
            review = self._invoke(
                self._config.fallback_model, system_prompt, user_content
            )
            return (
                f"> ⚠️ **Fallback model used** — the primary model "
                f"(`{self._config.model}`) failed, so this review was "
                f"generated by `{self._config.fallback_model}` instead.\n\n"
                + review
            )
        except Exception as fallback_error:
            print(
                f"Fallback model {self._config.fallback_model!r} also failed: "
                f"{fallback_error}"
            )
            return None

    def _invoke(self, model_id: str, system_prompt: str, user_content: str) -> str:
        """Invoke a specific model. Raises on failure."""
        provider = get_provider(model_id, self._config)
        return provider.invoke(model_id, system_prompt, user_content)

    def _build_system_prompt(self, rules_prompt: str = "", learnings_prompt: str = "") -> str:
        """Construct the system prompt from config + custom rules + learnings."""
        parts = [self._config.prompt]
        if rules_prompt:
            parts.append(rules_prompt)
        if learnings_prompt:
            parts.append(learnings_prompt)
        parts.append(f"Please answer in {self._config.language}.")
        return " ".join(parts)

    def _build_user_content(
        self, diff: str, previous_findings: Optional[str],
        context: Optional[str] = None, incremental_diff: str = "",
    ) -> str:
        """Build the user message content with optional context and prior findings."""
        parts: list[str] = []

        # Codebase context (referenced files) goes first so the model
        # has it in mind when reading the diff
        if context:
            parts.append(context)

        # The diff itself
        parts.append(diff)

        # Previous findings for resolution tracking
        if previous_findings:
            resolution_section = (
                "\n\n---\n"
                "PREVIOUS REVIEW FINDINGS (from the last push on this PR):\n"
            )

            # If we have an incremental diff, include it so the model
            # knows what actually changed since the last review
            if incremental_diff:
                resolution_section += (
                    "CHANGES SINCE LAST REVIEW (only new commits):\n"
                    f"{incremental_diff}\n\n"
                    "Use the above incremental changes to determine which "
                    "previous findings were addressed. A finding is resolved "
                    "if the incremental changes fix the concern — even if the "
                    "fix is in a related area rather than the exact original line.\n\n"
                )
            else:
                resolution_section += (
                    "Compare these against the current diff above. If a finding "
                    "has been addressed — even if the fix is in a related area of "
                    "the code rather than the exact line originally flagged — mark "
                    "it as resolved.\n\n"
                )

            resolution_section += (
                "Mark resolved findings with ✅ and strikethrough (~~text~~) in your "
                "new Findings section, e.g.:\n"
                "  ✅ ~~🟠 Major *Correctness* — `src/App.tsx`: missing null "
                "check~~ (resolved in this push)\n"
                "Only keep unresolved findings as active (without strikethrough). "
                "If ALL prior findings are resolved and no new ones exist, "
                "omit the Findings section entirely.\n\n"
                f"{previous_findings}\n"
                "---\n"
            )
            parts.append(resolution_section)

        return "\n\n".join(parts)
